[config]
schemaVersion = "0.0.1"

[package]
namespace = "innominata"
name = "Poglin"
versionNumber = "1.1.0"
description = "v1.1.0 Control base game speed. Replaces Peglin with Poglin in text."
websiteUrl = "https://github.com/innominata/Poglin"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_Peglin = "5.4.1901"

[build]
icon = "./Package/icon.png"
readme = "./Package/README.md"
outdir = "./"

[[build.copy]]
source = "./obj/Debug/net472/Poglin.dll"
target = "./Poglin.dll"
[publish]
repository = "https://thunderstore.io"
communities = ["peglin"]
categories = []
